version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
workflows:
  version: 2.1
  test:
    jobs:
      - test-35-20
      - test-35-21
      - test-35-22

      - test-36-20
      - test-36-21
      - test-36-22
      - test-36-30
      - test-36-31
      - test-36-32

      - test-37-20
      - test-37-21
      - test-37-22
      - test-37-30
      - test-37-31
      - test-37-32

      - test-38-20
      - test-38-21
      - test-38-22
      - test-38-30
      - test-38-31
      - test-38-32

      - test-39-20
      - test-39-21
      - test-39-22
      - test-39-30
      - test-39-31
      - test-39-32

      - done:
          requires:
            - test-39-32

jobs:
  base: &test-template
    docker:
      - image: circleci/python:3.4-stretch-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: python version
          command: python --version

      - restore_cache:
          keys:
          - v1-js
      - restore_cache:
          keys:
          - v1-py

      - run:
          name: JS deps 
          command: cd tests && yarn
      - save_cache:
          paths:
            - ./npm
          key: v1-js

      - run:
          name: setup python
          command: |
            python3 -m venv venv 
            source venv/bin/activate
            rm -f requirements.txt
            pip install -r tests/requirements/common.txt
            pip install -r tests/requirements/django${DJANGO_VERSION}.txt
      - save_cache:
          paths:
            - ./cache/pip
          key: v1-py

      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            cd tests
            coverage run --source=webpack_loader manage.py test

      - coveralls/upload:
          parallel: true

  test-35-20:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-stretch-node
    environment:
      DJANGO_VERSION: "20"
  test-35-21:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-stretch-node
    environment:
      DJANGO_VERSION: "21"
  test-35-22:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-stretch-node
    environment:
      DJANGO_VERSION: "22"

  test-36-20:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node
    environment:
      DJANGO_VERSION: "20"
  test-36-21:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node
    environment:
      DJANGO_VERSION: "21"
  test-36-22:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node
    environment:
      DJANGO_VERSION: "22"
  test-36-30:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node
    environment:
      DJANGO_VERSION: "30"
  test-36-31:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node
    environment:
      DJANGO_VERSION: "31"
  test-36-32:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node
    environment:
      DJANGO_VERSION: "32"

  test-37-20:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-node
    environment:
      DJANGO_VERSION: "20"
  test-37-21:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-node
    environment:
      DJANGO_VERSION: "21"
  test-37-22:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-node
    environment:
      DJANGO_VERSION: "22"
  test-37-30:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-node
    environment:
      DJANGO_VERSION: "30"
  test-37-31:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-node
    environment:
      DJANGO_VERSION: "31"
  test-37-32:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-node
    environment:
      DJANGO_VERSION: "32"

  test-38-20:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-buster-node
    environment:
      DJANGO_VERSION: "20"
  test-38-21:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-buster-node
    environment:
      DJANGO_VERSION: "21"
  test-38-22:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-buster-node
    environment:
      DJANGO_VERSION: "22"
  test-38-30:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-buster-node
    environment:
      DJANGO_VERSION: "30"
  test-38-31:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-buster-node
    environment:
      DJANGO_VERSION: "31"
  test-38-32:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-buster-node
    environment:
      DJANGO_VERSION: "32"

  test-39-20:
    <<: *test-template
    docker:
      - image: circleci/python:3.9-buster-node
    environment:
      DJANGO_VERSION: "20"
  test-39-21:
    <<: *test-template
    docker:
      - image: circleci/python:3.9-buster-node
    environment:
      DJANGO_VERSION: "21"
  test-39-22:
    <<: *test-template
    docker:
      - image: circleci/python:3.9-buster-node
    environment:
      DJANGO_VERSION: "22"
  test-39-30:
    <<: *test-template
    docker:
      - image: circleci/python:3.9-buster-node
    environment:
      DJANGO_VERSION: "30"
  test-39-31:
    <<: *test-template
    docker:
      - image: circleci/python:3.9-buster-node
    environment:
      DJANGO_VERSION: "31"
  test-39-32:
    <<: *test-template
    docker:
      - image: circleci/python:3.9-buster-node
    environment:
      DJANGO_VERSION: "32"

  done:
    docker:
      - image: 'circleci/node:10.0.0'
    steps:
      - coveralls/upload:
          parallel_finished: true
